### ISSUE TITLE
Unable to test decidim-module-antivirus

### ISSUE THREAD

**Issue by clauded** [mainio/decidim-module-antivirus#1]
Followed installation instruction of clamav and this module (add the gem, then bundle install). When I run "bundle exec rails ratonvirus:test" I get:
```
rails aborted!
Don't know how to build task 'ratonvirus:test' (See the list of available tasks with `rake --tasks`)
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

I guess some steps are missing for the installation instructions. I have the following gems installed:
```
Using ratonvirus 0.1.0
Using ratonvirus-clamby 0.1.0
Using decidim-antivirus 0.18.0
```

**Comment by ahukkanen** [comment]
Can you post your whole Gemfile, please?

**Comment by clauded** [comment]
Sorry for the noise, I found my problem: I need to specify my environment.
`RAILS_ENV=production bundle exec rails ratonvirus:test`
