### ISSUE TITLE
ETA for 0.19.0

### ISSUE THREAD

**Issue by clauded** [mainio/decidim-module-antivirus#2]
Do you have an ETA for a release compatible with Decidim 0.19.0?

**Comment by clauded** [comment]
Also, version 0.18.1 was released. I think the gemfile.lock could be adjusted so it's compatible with 0.18.x

**Comment by ahukkanen** [comment]
There is now a release for 0.19.x version of Decidim:
https://github.com/mainio/decidim-module-antivirus/releases/tag/v0.19.0
https://rubygems.org/gems/decidim-antivirus/versions/0.19.0

Regarding 0.18.1, decidim-antivirus v0.18.0 is already compatible with that as the core dependency is set to allow any point release in the mainline versions:
https://github.com/mainio/decidim-module-antivirus/blob/72549aecddf2ab78039daca0891d0c7d367ff7fd/lib/decidim/antivirus/version.rb#L6
