### ISSUE TITLE
Got an Error when tried to install Decidim-antiviurs

### ISSUE THREAD

**Issue by MohammedSalahadin** [mainio/decidim-module-antivirus#6]
Hello folks, I have included the gem "decidim-antivirus" to my gem file and saved correctly.
Once I tried to run the command bundle I got this error.
Here are some screen shots of the problem
![er1](https://user-images.githubusercontent.com/60615635/96008203-fde45a80-0e47-11eb-84fa-2dcdddeffb4c.PNG)
![er2](https://user-images.githubusercontent.com/60615635/96008275-12c0ee00-0e48-11eb-911d-b2c7012d12ca.PNG)

Error that I have got.
Bundler could not find compatible versions for gem "decidim-core":
  In snapshot (Gemfile.lock):
    decidim-core (= 0.22.0)

  In Gemfile:
    decidim-dev (= 0.22.0) was resolved to 0.22.0, which depends on
      decidim (= 0.22.0) was resolved to 0.22.0, which depends on
        decidim-core (= 0.22.0)

    decidim-antivirus was resolved to 0.14.4, which depends on
      decidim-core (~> 0.14.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by ahukkanen** [comment]
You have to update your `decidim-antivirus` version. It is following the core versioning.

For versions above `0.19.0` you have to fetch the release version from the GitHub repository's correct branch. See the repository branches for the core version you are targeting.

Bundler documentation on git dependencies:
https://bundler.io/guides/git.html
